FROM mcr.microsoft.com/playwright:v1.54.0-jammy

WORKDIR /app

COPY tools/scan-launcher/package.json /app/package.json
COPY tools/scan-launcher/start.js /app/start.js

RUN npm install

CMD ["npm", "run", "start"]
