ARG DOUYU_SCAN_RUNTIME_IMAGE=douyu-scan-provider-node:hotfix
FROM ${DOUYU_SCAN_RUNTIME_IMAGE}

WORKDIR /app

COPY tools/scan-launcher/package.json /app/package.json
COPY tools/scan-launcher/package-lock.json /app/package-lock.json
COPY tools/scan-launcher/start.js /app/start.js

CMD ["npm", "run", "start"]
