FROM debian:bookworm-slim

RUN printf '%s\n' \
	'deb http://mirrors.ustc.edu.cn/debian/ bookworm main contrib non-free non-free-firmware' \
	'deb http://mirrors.ustc.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware' \
	'deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware' \
	'deb http://mirrors.ustc.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware' \
	> /etc/apt/sources.list.d/ustc.list \
	&& rm -f /etc/apt/sources.list.d/debian.sources \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends ffmpeg ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
