worker_processes 1;

events {
  worker_connections 1024;
}

rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;

rtmp {
  server {
    listen 1935;
    chunk_size 4096;

    application live {
      live on;
      record off;
      push ${DOUYU_RELAY_FORWARD_URL};
    }
  }
}
