listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_server {
    enabled         off;
}
http_api {
    enabled         off;
}
vhost __defaultVhost__ {
    tcp_nodelay     on;
    min_latency     on;
    play {
        gop_cache   off;
    }
    publish {
        mr          off;
    }
    forward {
        enabled     on;
        destination ${DOUYU_RELAY_FORWARD_URL};
    }
}
